FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY minihttpd /app/minihttpd
EXPOSE 8080

CMD ["/app/minihttpd"]
